name: Supabase push migrations to production

on:
  release:
    types: [created]
    tags:
      - 'v*.*.*'

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ env.SUPABASE_DB_PASSWORD }}


jobs:
  supabase-push:
    steps:
      - uses: supabase/setup-cli@v1
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
